### ISSUE TITLE
Mongodb Localhost

### ISSUE THREAD

**Issue by oseiasgomes** [codequipo/TheDailyNews#1]
Hello,
I am testing this application. I like the idea, and I would like to test it out.
To use local Mongodb, it's giving an error,
Can you help me?

**Comment by talha1503** [comment]
Use this link for following the setup for mongodb atlas : https://codeforgeek.com/mongodb-atlas-node-js/ 
And accordingly fill your env file as given in the Readme . If you have still have any issues , contact any one of us .

`const uri = "mongodb+srv://<USERNAME>:<PASSWORD>@cluster0-1q7ty.mongodb.net/database"`

Use this username , password and set up your env file.
